#eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true

#服务配置
server:
  port: 9002
#spring配置
spring:
  #1.应用配置
  application:
    name: ihrm-system #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  #3.JPA
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  #4.Redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  #servlet
  servlet:
    multipart:
      max-file-size: 2MB     # 设置单个文件最大大小为2MB
      max-request-size: 2MB  # 设置多个文件大小为2MB
jwt:
  config:
    key: saas-ihrm
    ttl: 3600000
ai:
  appId: 84770411
  apiKey: qc8ZRud4ifEkQkKK3sOGv5sY
  secretKey: h2JGtFkzwpJ3CvWvPv5HJfzcrAAbqhW7
  imageType: BASE64
  groupId: itcast
qr:
  url: http://localhost:8080/#/facelogin
